config/routes.rb
Potter::Application.routes.draw do
  

  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords"}

  resources :invitations, only: [:index, :show] do
    collection do
      get :accept
    end 
  end

  resources :links, only: [:new, :create]
  
  resources :pots do
    resources :links, except: [:new, :show, :index], controller: 'pots/links'  do

      collection do
        get :archive
      end
    end
    resources :invitations, only: [:create, :new]
  end

  get '/pots/:id/links/new' => 'links#new'
  
  root to: "pots#index"
end

app/models/pot.rb
class Pot < ActiveRecord::Base
  include PublicActivity::Common
  
  has_many :links, -> {order created_at: :desc}
  has_many :old_links, -> {where("sent_at IS NOT ?", nil).order(created_at: :desc)}, class_name: "Link"
  has_many :new_links, -> {where("sent_at IS ?", nil).order(created_at: :desc)}, class_name: "Link"
  has_many :subscriptions
  has_many :users, through: :subscriptions

  WEEKDAYS = %w[monday tuesday wednesday thursday friday saturday sunday].freeze
  
  def markoff_new_links
    new_links.markoff
  end
  
  def next_delivery_date
    Chronic.parse("next #{delivery_day} at #{delivery_hour}", ambiguous_time_range: :none)
  end

  def new_members
    users.where("subscriptions.created_at > ?", last_delivered_at)
  end

  def cached_users_count
    Rails.cache.fetch([self, "users_count"]) { users.size }
  end

  def cached_users
    Rails.cache.fetch([self, "users"]) { users.to_a }
  end
end

app/controllers/pots/links_controller.rb
module Pots
  class LinksController < PotsController
    before_action :set_link, only: [:show, :edit, :update, :destroy]
    skip_before_action :set_pot

    def archive
      @links = current_pot.old_links.sent_directly_after(requested_date).decorate
    end


    # GET /links/1/edit
    def edit
    end

    # POST /links
    # POST /links.json
    def create
      @link = Link.new(link_params)
      @link.pot = current_pot
      @link.user = current_user
      
      respond_to do |format|
        if @link.save

          format.html do
            if params[:return_to].present?
              redirect_to params[:return_to]
            else
              redirect_to @link.pot, notice: 'Link wurde hinzugefügt.'
            end
          end
          format.json { render action: 'show', status: :created, location: @link }
        else
          format.html { render action: 'pots/new' }
          format.json { render json: @link.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /links/1
    # PATCH/PUT /links/1.json
    def update
      respond_to do |format|
        if @link.update(link_params)
          format.html { redirect_to @link.pot, flash: {success: 'Link wurde aktualisiert.'} }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @link.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /links/1
    # DELETE /links/1.json
    def destroy
      @link.destroy
      flash[:success] = "Link gelöscht!"
      respond_to do |format|
        format.html { redirect_to pot_path(@link.pot) }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_link
        @link = Link.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def link_params
        params.require(:link).permit(:name, :url, :description, :hottiness)
      end
      
      def current_pot
        @current_pot ||= current_user.pots.find(params[:pot_id])
      end
      helper_method :current_pot


      def requested_date
        CalendarWeek.new(Date.strptime(params[:calendar_week] + params[:year], "%W%Y"))
      rescue
        CalendarWeek.new(current_pot.last_delivered_at)
      end
      helper_method :requested_date

      class CalendarWeek
        delegate :to_date, :to_datetime, :strftime, :year, to: :monday

        def initialize(date)
          @monday = date.beginning_of_week
        end

        def monday
          @monday
        end

        def to_s
          @monday.strftime("%W").to_s
        end

        def to_str
          to_s
        end
      end
  end
end

app/controllers/pots_controller.rb
class PotsController < ApplicationController
  before_action :set_pot, only: [:show, :edit, :update, :destroy]

  # GET /pots
  # GET /pots.json
  def index
    @pots = current_user.pots
  end

  # GET /pots/1
  # GET /pots/1.json
  def show
    @link = Link.new(pot: @pot)#@pot.links.build
  end

  # GET /pots/new
  def new
    @pot = Pot.new
  end

  # GET /pots/1/edit
  def edit
  end

  # POST /pots
  # POST /pots.json
  def create
    @pot = Pot.new(pot_params)
    @pot.users << current_user
    respond_to do |format|
      if @pot.save
        format.html { redirect_to @pot, notice: 'Pott wurde erstellt.' }
        format.json { render action: 'show', status: :created, location: @pot }
      else
        format.html { render action: 'new' }
        format.json { render json: @pot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pots/1
  # PATCH/PUT /pots/1.json
  def update
    respond_to do |format|
      if @pot.update(pot_params)
        format.html { redirect_to @pot, notice: 'Pott wurde aktualisiert.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pots/1
  # DELETE /pots/1.json
  def destroy
    @pot.destroy
    respond_to do |format|
      format.html { redirect_to pots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pot
      @pot ||= current_user.pots.find(params[:pot_id] || params[:id]).decorate
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pot_params
      params.require(:pot).permit(:name, :delivery_day, :delivery_hour)
    end
end

app/helpers/pots_helper.rb
module PotsHelper
  def random_illustration
    illustrations = %w(bag.png book.png calendar.png  clipboard.png colors.png compass.png gift.png infinity.png  mail.png map.png paper.png retina.png share.png time.png)
    raw image_tag("/illustrations/#{illustrations.sample}", class: "illustrations")
  end
end

app/views/pots/_form.html.erb
<%= simple_form_for(@pot) do |f| %>
  <% if @pot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pot.errors.count, "error") %> prohibited this pot from being saved:</h2>

      <ul>
      <% @pot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, input_html: {class: "span5"} %>
  <%= f.input :delivery_day, collection: Pot::WEEKDAYS, input_html: {class: "span5"}  %>
  <%= f.input :delivery_hour, collection: (1..24).map {|h| [h.to_s + ":00 Uhr",h]}, input_html: {class: "span5"} %>

  <div class="control-group">
    <div class="controls">
        <%= f.button :submit, class: "span3" %>
    </div>
  </div>
<% end %>

app/views/pots/edit.html.erb
<% content_for :breadcrump do %>
  <%= breadcrump(link_to("Potts", pots_path), link_to("„" + @pot.name + "“", pot_path(@pot)), "Einstellungen") %>
<% end %>
<h1>Einstellungen von „<%= @pot.name %>“</h1>

<%= render 'form' %>

app/views/pots/index.html.erb
<div class="fluid-container" id="main-content">
  <div class="container">
    <div class="row with-space">
      <div class="span12">
        <h1>Deine Potts</h1>
      </div>
    </div>
    <div class="row with-space">
      <% @pots.each do |pot| %>
        <div class="span3">
          <div class="tile pots">
            <h3><%= pot.name %></h3>
            <small class="subheading">erstellt von <%= pot.users.first.name %></small>
            <%= link_to "Anzeigen", pot, class: "btn btn-primary btn-large btn-block" %>
          </div>
        </div>
      <% end %>
      <div class="span3">
        <div class="tile new_pot pots">
          <h3>Neuer Pott</h3>
          <small class="subheading">Für dich und deine Freunde</small>

          <%= link_to 'Erstellen', new_pot_path, class: "btn btn-large btn-block btn-primary" %>
        </div>
      </div>
    </div>
    <div class="row with-space">
      <div class="span3">
      </div>
    </div>
  </div>
</div>

app/views/pots/new.html.erb
<% content_for :toplinks do %>
  <%= link_to raw('&laquo; alle Potts'), pots_path %>
<% end %>
<h1>Neuer Pott</h1>
<%= render 'form' %>

app/views/pots/show.html.erb
<% content_for :breadcrump do %>
  <%= breadcrump(link_to("Potts", pots_path), @pot.name) %>
<% end %>

<header>
  <%= link_to "einladen", new_pot_invitation_path(@pot), class: "pull-right" %>
  <h1>
    <%= @pot.name %>
    <small><%= link_to raw('<i class="icon-cog"></i>'), edit_pot_path(@pot), class: "muted" %></small>
  </h1>

  <nav class="sub_pot_nav">
    <ul>
      <li>Übersicht</li>
      <li><%= link_to "Archiv", archive_pot_links_path(@pot) %></li>
    </ul>
  </nav>
</header>

<p class="lead">
  Dieser Pott sendet jeden <strong><%= t @pot.delivery_day %></strong> um  <strong><%= @pot.delivery_hour %></strong> eine Zusammenfassung an <strong><span title="<%= @pot.cached_users.map(&:name).join(", ") %>"><%= t ".people", count: @pot.cached_users_count %></span></strong>!
</p>

<section>
  <%= render partial: 'pots/links/new_form' %>
  <section>
    <div class="row">
      <div class="span12">
        <h2>Deine Links für nächsten <%= t @pot.delivery_day %></h2>


        <% cache(["new_links", @pot]) do %>
          <% if @pot.new_links.any? %>
            <table class="table table-bordered" id="pot_links">
              <thead>
                <tr>
                  <th class="link_sent"></th>
                  <th>Link</th>
                  <th>Autor</th>
                  <th>Hinzugefügt am</th>
                  <th>Hottiness</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: 'pots/links/link', collection:  @pot.new_links.from_user(current_user).decorate %>
              </tbody>
            </table>
          <% else %>
            <p class="palette no_links palette-silver">
              Du hast diese Woche noch keine Links gesammelt.
            <% if @pot.new_links.from_others_than(current_user).any? %>
                <br>
                <strong>Halt dich ran, die anderen haben in dieser Woche schon <%= pluralize(@pot.new_links.from_others_than(current_user).count, "Link") %> gesammelt!</strong>
            <% end %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
</section>