config/routes.rb
Potter::Application.routes.draw do
  

  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords"}

  resources :invitations, only: [:index, :show] do
    collection do
      get :accept
    end 
  end

  resources :links, only: [:new, :create]
  
  resources :pots do
    resources :links, except: [:new, :show, :index], controller: 'pots/links'  do

      collection do
        get :archive
      end
    end
    resources :invitations, only: [:create, :new]
  end

  get '/pots/:id/links/new' => 'links#new'
  
  root to: "pots#index"
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :pot
  belongs_to :issuer, foreign_key: :user_id, class_name: 'User'
  before_validation :generate_token, on: :create
  validates :issuer, :pot, :token, :email, presence: true
  
  def user_is_already_member?
  end
  
  def accept!(invited_user)
    return false unless invited_user.is_a?(User) && pot.users.include?(issuer)

    @invited_user = invited_user

    add_user_to_pot do
      track_subscription
      destroy
    end
    true
  end

  def issuer_name
    self.issuer.name
  end

  def pot_name
    self.pot.name
  end

  private

  def track_subscription
    self.pot.create_activity key: "pot.new_member", owner: @invited_user
  end

  def add_user_to_pot
    pot.users << @invited_user
    if pot.save!
      yield
    end
  end

  def generate_token
    begin
      self.token = SecureRandom.hex
    end while self.class.exists?(token: token)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: [:show]
  
  # GET /invitations
  def index
    @invitations = Invitation.all
  end

  # GET /invitations/1
  def show
  end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # POST /invitations
  def create
    @invitation = Invitation.new(invitation_params)
    @invitation.issuer = current_user
    @invitation.pot = current_pot
    
    if @invitation.save
      InvitationNotifier.new(@invitation).send_invitation
      redirect_to current_pot, notice: 'Einladung erfolgreich abgeschickt.'
    else
      render action: 'new'
    end
  end
  
  def accept
    @invitation = Invitation.find_by_token(params[:token])
    if @invitation.blank?
      redirect_to root_path, flash: {error: 'Da ist etwas grundlegend schief gelaufen, das tut uns leid :-('}
    elsif @invitation.accept!(current_user)
      redirect_to @invitation.pot, flash: {success: 'Einladung angenommen!'}
    else
      redirect_to  @invitation.pot, notice: 'Du sitzt doch schon im Pott!'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = current_pot.invitations.find(params[:id])
    end
    
    def current_pot
      @current_pot ||= Pot.find(params[:pot_id])
    end
    helper_method :current_pot

    # Never trust parameters from the scary internet, only allow the white list through.
    def invitation_params
      params.require(:invitation).permit(:email)
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/edit.html.erb
<%= simple_form_for(@invitation) do |f| %>
  <%= f.error_notification %>

  <%= f.input :email %>
  
  <div class="control-group">
    <div class="controls">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/invitations/index.html.erb
<h1>Listing invitations</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
    <tr>
      <td><%= link_to 'Show', invitation %></td>
      <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
      <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>Einladung senden</h1>

<p class="lead">
  Hier kannst du neue Leute für den Pott „<%= current_pot.name %>“ einladen!
</p>

<%= simple_form_for([current_pot, @invitation]) do |f| %>
  <%= f.error_notification %>

  <%= f.input :email %>
  
  <div class="control-group">
    <div class="controls">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>