config/routes.rb
Potter::Application.routes.draw do
  

  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords"}

  resources :invitations, only: [:index, :show] do
    collection do
      get :accept
    end 
  end

  resources :links, only: [:new, :create]
  
  resources :pots do
    resources :links, except: [:new, :show, :index], controller: 'pots/links'  do

      collection do
        get :archive
      end
    end
    resources :invitations, only: [:create, :new]
  end

  get '/pots/:id/links/new' => 'links#new'
  
  root to: "pots#index"
end

app/models/link.rb
class Link < ActiveRecord::Base
  include PublicActivity::Common
  
  HOTTINESSES = {1 => "interesting for some of us", 2 => "interesting for everybody", 3 => "just. fucking. read. it."}
  
  belongs_to :pot, touch: true
  belongs_to :user
  
  scope :from_user, lambda {|user| where("user_id = ?", user.id)}
  scope :from_others_than, lambda {|user| where("user_id != ?", user.id)}
  scope :sent_directly_after, -> time { where(sent_at: where("sent_at >= ?", time.to_datetime).order("sent_at ASC").limit(1).pluck(:sent_at))}

  validates :user, presence: true
  # validates :pot, presence: true
  validates :hottiness, inclusion: {in: HOTTINESSES}
  
  def self.markoff
    self.update_all(sent_at: Time.zone.now)
  end
  
  def sent?
    self.sent_at.present?
  end

  def cached_user_name
    Rails.cache.fetch([self, "user_name"]) { user.name }
  end
end

app/models/pot.rb
class Pot < ActiveRecord::Base
  include PublicActivity::Common
  
  has_many :links, -> {order created_at: :desc}
  has_many :old_links, -> {where("sent_at IS NOT ?", nil).order(created_at: :desc)}, class_name: "Link"
  has_many :new_links, -> {where("sent_at IS ?", nil).order(created_at: :desc)}, class_name: "Link"
  has_many :subscriptions
  has_many :users, through: :subscriptions

  WEEKDAYS = %w[monday tuesday wednesday thursday friday saturday sunday].freeze
  
  def markoff_new_links
    new_links.markoff
  end
  
  def next_delivery_date
    Chronic.parse("next #{delivery_day} at #{delivery_hour}", ambiguous_time_range: :none)
  end

  def new_members
    users.where("subscriptions.created_at > ?", last_delivered_at)
  end

  def cached_users_count
    Rails.cache.fetch([self, "users_count"]) { users.size }
  end

  def cached_users
    Rails.cache.fetch([self, "users"]) { users.to_a }
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

 
  # GET /links/new
  def new
    @link = LinkCreator.new(name: params[:name], url: params[:url])
  end

  # POST /links
  # POST /links.json
  def create
    @link = LinkCreator.new(link_params)
    Rails.logger.debug(link_params)

    @link.user = current_user
    
    respond_to do |format|
      if @link.save

        format.html do
          if params[:return_to].present?
            redirect_to params[:return_to]
          else
            redirect_to root_url, notice: 'Link wurde hinzugefügt.'
          end
        end
        format.json { render action: 'show', status: :created, location: @link }
      else
        format.html { render action: 'pots/new' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:name, :url, :description, :hottiness, pot_ids: [  ])
    end
end

app/controllers/pots/links_controller.rb
module Pots
  class LinksController < PotsController
    before_action :set_link, only: [:show, :edit, :update, :destroy]
    skip_before_action :set_pot

    def archive
      @links = current_pot.old_links.sent_directly_after(requested_date).decorate
    end


    # GET /links/1/edit
    def edit
    end

    # POST /links
    # POST /links.json
    def create
      @link = Link.new(link_params)
      @link.pot = current_pot
      @link.user = current_user
      
      respond_to do |format|
        if @link.save

          format.html do
            if params[:return_to].present?
              redirect_to params[:return_to]
            else
              redirect_to @link.pot, notice: 'Link wurde hinzugefügt.'
            end
          end
          format.json { render action: 'show', status: :created, location: @link }
        else
          format.html { render action: 'pots/new' }
          format.json { render json: @link.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /links/1
    # PATCH/PUT /links/1.json
    def update
      respond_to do |format|
        if @link.update(link_params)
          format.html { redirect_to @link.pot, flash: {success: 'Link wurde aktualisiert.'} }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @link.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /links/1
    # DELETE /links/1.json
    def destroy
      @link.destroy
      flash[:success] = "Link gelöscht!"
      respond_to do |format|
        format.html { redirect_to pot_path(@link.pot) }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_link
        @link = Link.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def link_params
        params.require(:link).permit(:name, :url, :description, :hottiness)
      end
      
      def current_pot
        @current_pot ||= current_user.pots.find(params[:pot_id])
      end
      helper_method :current_pot


      def requested_date
        CalendarWeek.new(Date.strptime(params[:calendar_week] + params[:year], "%W%Y"))
      rescue
        CalendarWeek.new(current_pot.last_delivered_at)
      end
      helper_method :requested_date

      class CalendarWeek
        delegate :to_date, :to_datetime, :strftime, :year, to: :monday

        def initialize(date)
          @monday = date.beginning_of_week
        end

        def monday
          @monday
        end

        def to_s
          @monday.strftime("%W").to_s
        end

        def to_str
          to_s
        end
      end
  end
end

app/controllers/pots_controller.rb
class PotsController < ApplicationController
  before_action :set_pot, only: [:show, :edit, :update, :destroy]

  # GET /pots
  # GET /pots.json
  def index
    @pots = current_user.pots
  end

  # GET /pots/1
  # GET /pots/1.json
  def show
    @link = Link.new(pot: @pot)#@pot.links.build
  end

  # GET /pots/new
  def new
    @pot = Pot.new
  end

  # GET /pots/1/edit
  def edit
  end

  # POST /pots
  # POST /pots.json
  def create
    @pot = Pot.new(pot_params)
    @pot.users << current_user
    respond_to do |format|
      if @pot.save
        format.html { redirect_to @pot, notice: 'Pott wurde erstellt.' }
        format.json { render action: 'show', status: :created, location: @pot }
      else
        format.html { render action: 'new' }
        format.json { render json: @pot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pots/1
  # PATCH/PUT /pots/1.json
  def update
    respond_to do |format|
      if @pot.update(pot_params)
        format.html { redirect_to @pot, notice: 'Pott wurde aktualisiert.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pots/1
  # DELETE /pots/1.json
  def destroy
    @pot.destroy
    respond_to do |format|
      format.html { redirect_to pots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pot
      @pot ||= current_user.pots.find(params[:pot_id] || params[:id]).decorate
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pot_params
      params.require(:pot).permit(:name, :delivery_day, :delivery_hour)
    end
end

app/helpers/links_helper.rb
module LinksHelper
  def archive_weeks
    Link.where(pot_id: current_pot).uniq(:sent_at).order(sent_at: :desc).pluck(:sent_at).compact.map{|date| Pots::LinksController::CalendarWeek.new(date)}
  end

  def archive_weeks_grouped_by_years_and_months
    years = archive_weeks_grouped_by_years
    archive_weeks_grouped_by_years.each do |year, weeks|
      years[year] = weeks.group_by do |week|
        week.strftime("%B")
      end
    end
    years
  end

  def archive_weeks_grouped_by_years
    archive_weeks.group_by do |week|
      week.strftime("%Y")
    end
  end
end

app/helpers/pots_helper.rb
module PotsHelper
  def random_illustration
    illustrations = %w(bag.png book.png calendar.png  clipboard.png colors.png compass.png gift.png infinity.png  mail.png map.png paper.png retina.png share.png time.png)
    raw image_tag("/illustrations/#{illustrations.sample}", class: "illustrations")
  end
end

app/views/pots/links/_link.html.erb
<tr id="link_<%= link.id %>">
  <% if link.sent? %>
    <td title="<%= link.sent_at %>" class="link_sent palette-success"><span class="fui-checkmark-24"></span></td>
  <% else %>
    <td title="<%= @pot.next_delivery_date %>" class="link_sent palette-info"><span class="fui-time-24"></span></td>
  <% end %>
  <td><%= link_to link.name, link.url, target: "_blank" %></td>
  <td><%= link.cached_user_name %></td>
  <td><%= l link.created_at, format: :short %></td>
  <td><span class="label label-<%= link.hottiness_label %>"><%= link.hottiness %></span></td>
  <td><%= link_to "bearbeiten", edit_pot_link_path(@pot, link) %> | <%= link_to "löschen", pot_link_path(@pot, link), method: :delete %></td>
</tr>

app/views/pots/links/_new_form.html.erb
<section>
  <div class="row">
    <div class="span12">
      <%= simple_form_for [@pot, @link], html: {class: "well new_link_form"} do |f| %>
        <header>
          <h3>Neuen Link hinzufügen</h3>
          <span class="bookmarklet">Bookmarklet: <%= link_to "zu Potter hinzufügen", "javascript:" + u(render(partial: "links/bookmarklet", formats: :js)), class: "newlink", title: "Ziehe diesen Button einfach in deine Lesezeichenleiste, um jederzeit schnell und bequem neue Links zu deinen Potts hinzuzufügen!" %></span>
        </header>
        
        <%= f.input :name, placeholder: "Titel", input_html: {class: "span9"}  %>
        <%= f.input :url, placeholder: "example.com", input_html: {class: "span9"} %>
        <%= f.input :description, placeholder: "Lorem ipsum...", input_html: {class: "span9"}  %>
      
        <%= f.input :hottiness, label: 'Empfehlungsstufe', collection: {"interessant" => 1, "lesen!" => 2, "Lesebefehl!!!" => 3}, input_html: {class: "span3"}, include_blank: false %>
        <%= hidden_field_tag :return_to, params[:url] if params[:url].present? %>
        <div class="control-group">
          <div class="controls">
            <% if params[:url].present? %>
              <%= f.submit "Link erstellen und zu #{params[:url].split('/')[2]} zurückkehren", class: "btn btn-large btn-primary" %>
            <% else %>
              <%= f.submit "Link hinzufügen" , class: "btn btn-large span3 btn-primary " %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/pots/links/archive.html.erb
<section>
  <header>
    <%= link_to "einladen", new_pot_invitation_path(current_pot), class: "pull-right" %>
    <h1>
      <%= current_pot.name %>
      <small><%= link_to raw('<i class="icon-cog"></i>'), edit_pot_path(@pot), class: "muted" %></small>
    </h1>

    <nav class="sub_pot_nav">
      <ul>
        <li><%= link_to "Übersicht", current_pot %></li>
        <li>Archiv</li>
      </ul>
    </nav>
  </header>
  <div class="row">
    <div class="span12">
      <h2>Archiv</h2>

      <%# raw archive_weeks.map{|date| link_to("vor #{((Date.today - date).days / (60 * 60 * 24 * 7)).to_i} Wochen", archive_pot_links_path(current_pot, archive_week: date.iso8601)) }.join(', ') %>

      <div class="archive_picker">
        <ul>
          <% archive_weeks_grouped_by_years_and_months.each do |year, months| %>
            <li>
              <h3><%= year %></h3>
              <ul>
                <% months.each do |month, weeks| %>
                  <li>
                    <%= month %>
                    <ul>
                      <% weeks.each do |week| %>
                      <li>
                        <%= link_to(week, archive_pot_links_path(current_pot, calendar_week: week, year: week.year)) %>
                      </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
      <%# cache([current_pot, requested_date]) do %>
        <table class="table table-bordered" id="pot_links">
          <thead>
            <tr>
              <th class="link_sent"></th>
              <th>Link</th>
              <th>Autor</th>
              <th>Hinzugefügt am</th>
              <th>Hottiness</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: 'link', collection:  @links %>
          </tbody>
        </table>
        <%# will_paginate @links, inner_window: 8 %>
      <%# end %>
    </div>
  </div>
</section>

app/views/pots/links/edit.html.erb
<section>
  <div class="row">
    <div class="span12">
      <%= simple_form_for [@pot, @link], html: {class: "well new_link_form"} do |f| %>
        <header>
          <h3>Link bearbeiten</h3>
          <span class="bookmarklet">Bookmarklet: <%= link_to "neuer Link für #{@pot.name}", "javascript:" + u(render(partial: "pots/bookmarklet", formats: :js)), class: "newlink", title: "Ziehe diesen Button einfach in deine Lesezeichenleiste, um jederzeit schnell und bequem neue Links zu diesem Pott hinzuzufügen!" %></span>
        </header>
        
        <%= f.input :name, placeholder: "Titel", input_html: {class: "span9"}  %>
        <%= f.input :url, placeholder: "example.com", input_html: {class: "span9"} %>
        <%= f.input :description, placeholder: "Lorem ipsum...", input_html: {class: "span9"}  %>
      
        <%= f.input :hottiness, collection: {"gut" => 1, "nicer Shit!" => 2, "Lesebefehl!" => 3}, input_html: {class: "span3"}, include_blank: false %>
        <%= hidden_field_tag :return_to, params[:url] if params[:url].present? %>
        <div class="control-group">
          <div class="controls">
            <%= f.submit "Link aktualisieren" , class: "btn btn-large span3 btn-primary " %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/pots/links/index.html.erb
<h1>Listing links</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>References</th>
      <th>References</th>
      <th>Already shared</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
    <tr>
      <td><%= link.name %></td>
      <td><%= link.url %></td>
      <td><%= link.references %></td>
      <td><%= link.references %></td>
      <td><%= link.already_shared %></td>
      <td><%= link_to 'Show', link %></td>
      <td><%= link_to 'Edit', edit_link_path(link) %></td>
      <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/pots/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @link.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<p>
  <strong>References:</strong>
  <%= @link.references %>
</p>

<p>
  <strong>References:</strong>
  <%= @link.references %>
</p>

<p>
  <strong>Already shared:</strong>
  <%= @link.already_shared %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>